on: [pull_request]

jobs:
  preview-app-action:
    runs-on: ubuntu-latest
    name: Preview app
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Preview app action
      uses: ./.github/actions/preview-app-action
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        body-template: '[Preview App](https://app.dev.linkfire.co/index.html:pull-%pr_number%)'
