name: "Update Pull Request"

on: pull_request

jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: preview-app-action@v1.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          body-template: '[Preview App](https://app.dev.linkfire.co/index.html:pull-%pr_number%)'
         
