on: [pull_request]

jobs:
  preview-app-action:
    runs-on: ubuntu-latest
    name: Preview app
    steps:
    - name: Preview app action step
      id: preview
      uses: Mi6u3l/preview-app-action@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        body-template: '[Preview App](https://app.dev.linkfire.co/index.html:pull-%pr_number%)'
